services:
  - type: web
    name: my-friend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    branch: master   # ✅ change this to your actual branch
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
