server:
  port: ${PORT:8080}  # Render injects port

spring:
  jmx:
    enabled: false
  data:
    mongodb:
      uri: mongodb+srv://sjroot9:gvBZZkzcKXWGGRru@recharge.xniae.mongodb.net/my_friend?retryWrites=true&w=majority
      auto-index-creation: false  # 🚀 speed up startup
  security:
    user:
      name: ${SPRING_ADMIN_USER:admin}
      password: ${SPRING_ADMIN_PASSWORD:admin123}
  main:
    banner-mode: off
    allow-circular-references: true
    lazy-initialization: true     # 🚀 lazy init for faster startup

app:
  jwt:
    secret: ${JWT_SECRET:0A6DHDpE3Cqdwe7JXm7c1SPRki0moOwfKBaB5aZ5zmM=}
    expiration-ms: 86400000
  websocket:
    endpoint: /ws
    allowed-origins: "*"
    broker-prefix: /topic
    user-destination-prefix: /user
    enable-simple-broker: false   # 🚀 skip simple broker in prod

logging:
  level:
    root: INFO
    com.communication.app: INFO
    org.springframework.security: INFO
    sun.rmi: WARN
    javax.management.remote.rmi: WARN

  file:
    name: logs/communication-app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,ready
  endpoint:
    health:
      show-details: never


health:
  check: https://myfriend-frontend-eight.vercel.app/actuator/ready